"use client";
/* eslint-disable @next/next/no-img-element -- Private media previews require authenticated requests. */
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Film, List, MessageSquare, Upload, Pencil, Trash2 } from "lucide-react";
import { SERVICE_CATEGORIES, type Service, type GalleryVideo, type Review } from "@/lib/content-types";
import { postJson, uploadFile } from "@/lib/upload-client";

type Asset = { id: string; purpose: string; kind: string; status: string; bytes: number | null; createdAt: string };
export function AdminContent({ services, videos, reviews, assets, uploadsEnabled }: { services: Service[]; videos: GalleryVideo[]; reviews: Review[]; assets: Asset[]; uploadsEnabled: boolean }) {
  const router = useRouter();
  const [tab, setTab] = useState("services"), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [service, setService] = useState<Service | null>(null), [video, setVideo] = useState<GalleryVideo | null>(null);
  const [videoId, setVideoId] = useState<string | null>(null), [coverId, setCoverId] = useState<string | null>(null), [progress, setProgress] = useState("");
  const [reviewFilter, setReviewFilter] = useState("pending");
  async function action(body: unknown, success: string) {
    setBusy(true); setError(""); setMessage("");
    try { await postJson("/api/admin/content", body); setMessage(success); router.refresh(); return true; }
    catch (e) { setError(e instanceof Error ? e.message : "Could not save changes."); return false; }
    finally { setBusy(false); }
  }
  async function saveService(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    if (await action({ entity: "service", id: service?.id, name: data.get("name"), description: data.get("description"), category: data.get("category"), position: Number(data.get("position")), active: data.get("active") === "on" }, "Service saved. The website and booking form are updated.")) setService(null);
  }
  async function saveVideo(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget, data = new FormData(form);
    setBusy(true); setError(""); setMessage("");
    try {
      let asset = videoId || video?.assetId || null, cover = coverId || video?.coverId || null;
      const file = data.get("video") as File, photo = data.get("cover") as File;
      if (file?.size && !videoId) { asset = await uploadFile(file, "gallery", p => setProgress(`Video upload: ${p}%`)); setVideoId(asset); }
      if (photo?.size && !coverId) { cover = await uploadFile(photo, "cover", p => setProgress(`Cover upload: ${p}%`)); setCoverId(cover); }
      await postJson("/api/admin/content", { entity: "gallery", id: video?.id, title: data.get("title"), description: data.get("description"), ceremony: data.get("ceremony"), location: data.get("location"), position: Number(data.get("position")), active: data.get("active") === "on", assetId: asset, coverId: cover });
      setMessage("Video saved. Published items appear in the single-player gallery."); setVideo(null); setVideoId(null); setCoverId(null); form.reset(); router.refresh();
    } catch (e) { setError(e instanceof Error ? e.message : "Video upload failed."); } finally { setBusy(false); setProgress(""); }
  }
  const selectedReviews = reviews.filter(r => reviewFilter === "all" || r.status === reviewFilter);
  return <div className="content-manager">
    <nav className="manager-tabs" aria-label="Manage website">{[{ key: "services", name: "Services", icon: List }, { key: "media", name: "Media", icon: Film }, { key: "reviews", name: `Reviews (${reviews.filter(r => r.status === "pending").length} pending)`, icon: MessageSquare }].map(item => <button key={item.key} type="button" disabled={busy} aria-pressed={tab === item.key} onClick={() => { setTab(item.key); setMessage(""); setError(""); }}><item.icon size={18} aria-hidden="true" />{item.name}</button>)}</nav>
    {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="manager-success" role="status">{message}</p>}{progress && <p role="status">{progress}</p>}
    {tab === "services" && <div className="manager-columns"><section className="manager-panel"><h2>{service ? "Edit ceremony" : "Add a ceremony"}</h2><p>Names and categories appear on the homepage and booking form. Disable a service to remove it without changing historical bookings.</p>
      <form key={service?.id || "new-service"} onSubmit={saveService}><fieldset disabled={busy}><label>Service name<input name="name" defaultValue={service?.name} minLength={2} maxLength={80} placeholder="e.g. Durga Path" required /></label><label>Category<select name="category" defaultValue={service?.category || "Pujas & Path"}>{SERVICE_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label>Short description<textarea name="description" defaultValue={service?.description} minLength={15} maxLength={500} rows={4} required /></label><label>Display order<input name="position" type="number" min={0} max={999} defaultValue={service?.position ?? services.length + 1} required /></label><label className="consent-check"><input type="checkbox" name="active" defaultChecked={service?.active ?? true} /><span>Available on the website and booking form</span></label><button type="submit">{busy ? "Saving..." : "Save service"}</button>{service && <button type="button" className="secondary-button" onClick={() => setService(null)}>Cancel editing</button>}</fieldset></form>
    </section><section className="manager-panel"><h2>Service catalogue</h2><div className="manager-items">{services.map(s => <article key={s.id}><div><span className="status-tag">{s.active ? "Available" : "Disabled"}</span><h3>{s.name}</h3><p>{s.category} · Order {s.position}</p></div><div className="manager-actions"><button disabled={busy} onClick={() => setService(s)}><Pencil size={15} />Edit</button><button disabled={busy} onClick={() => action({ entity: "service", ...s, active: !s.active }, s.active ? "Service disabled. Existing bookings are unchanged." : "Service enabled.")}>{s.active ? "Disable" : "Enable"}</button></div></article>)}</div></section></div>}
    {tab === "media" && <><div className="manager-columns"><section className="manager-panel"><h2>{video ? "Edit video" : "Add a gallery video"}</h2><p>Video: MP4/WebM, up to 50 MB and 2 minutes. Optional cover: JPG/PNG/WebP, up to 3 MB. Uploads are private until you publish the gallery item.</p>{!uploadsEnabled && <p className="form-error">Cloudinary is not configured. You can edit existing gallery items, but cannot upload new files yet.</p>}
      <form key={video?.id || "new-video"} onSubmit={saveVideo}><fieldset disabled={busy}><label>Video title<input name="title" defaultValue={video?.title} minLength={3} maxLength={100} required /></label><label>Short description<textarea name="description" defaultValue={video?.description} minLength={5} maxLength={500} rows={3} required /></label><label>Ceremony<input name="ceremony" list="ceremony-names" defaultValue={video?.ceremony || "Ganga Aarti"} minLength={2} maxLength={100} required /><datalist id="ceremony-names">{services.map(s => <option key={s.id} value={s.name} />)}</datalist></label><label>Location (optional)<input name="location" defaultValue={video?.location} maxLength={120} placeholder="City or venue, without private addresses" /></label><label>{video ? "Replace video (optional)" : "Video file"}<input name="video" type="file" accept="video/mp4,video/webm" disabled={!uploadsEnabled} onChange={() => setVideoId(null)} required={!video && !videoId} /></label><label>Cover photo (optional)<input name="cover" type="file" accept="image/jpeg,image/png,image/webp" disabled={!uploadsEnabled} onChange={() => setCoverId(null)} /></label><label>Display order<input type="number" name="position" min={0} max={999} defaultValue={video?.position ?? videos.length + 1} required /></label><label className="consent-check"><input type="checkbox" name="active" defaultChecked={video?.active ?? false} /><span>Publish in the website gallery</span></label><button type="submit"><Upload size={16} />{busy ? "Uploading / saving..." : "Save video"}</button>{video && <button type="button" className="secondary-button" onClick={() => { setVideo(null); setVideoId(null); setCoverId(null); }}>Cancel editing</button>}</fieldset></form>
    </section><section className="manager-panel"><h2>Video library</h2><div className="manager-items">{videos.map(v => <article key={v.id}><video src={v.src} poster={v.poster} controls playsInline preload="none" /><h3>{v.title}</h3><p>{v.ceremony} {v.location && `· ${v.location}`}</p><span className="status-tag">{v.active ? "Published" : "Hidden"} · Order {v.position}</span><div className="manager-actions"><button disabled={busy} onClick={() => { setVideo(v); setVideoId(null); setCoverId(null); }}><Pencil size={15} />Edit</button><button disabled={busy} onClick={() => action({ entity: "gallery", ...v, active: !v.active }, "Visibility updated.")}>{v.active ? "Hide" : "Publish"}</button><button disabled={busy} onClick={() => { if (confirm("Remove this video from the gallery and permanently delete its uploaded video and cover?")) void action({ entity: "gallery", action: "delete", id: v.id }, "Video removed."); }}><Trash2 size={15} />Remove</button></div></article>)}</div></section></div>
      <details className="manager-panel storage-panel"><summary>Manage stored uploads and incomplete uploads</summary><p>Daily upload reservations are capped at 160 MB across the website. This is not your Cloudinary account usage. Check actual storage, bandwidth, and credits in your Cloudinary dashboard. Delete abandoned or rejected attachments below to recover storage. Deleting a gallery attachment hides that gallery item.</p><p>The latest 100 uploads are shown, including uploads not yet attached to a saved video.</p>{assets.map(a => <div className="asset-row" key={a.id}><span>{a.purpose} / {a.kind} · {a.status} · {a.bytes ? `${(a.bytes / 1024 / 1024).toFixed(1)} MB` : "Incomplete upload"}<small>{new Date(a.createdAt).toLocaleDateString()} · {a.id.slice(0, 8)}</small></span><button disabled={busy} onClick={() => { if (confirm("Permanently delete this uploaded file? This cannot be undone.")) void action({ entity: "asset", action: "delete", id: a.id }, "Attachment deleted."); }}>Delete file</button></div>)}</details>
    </>}
    {tab === "reviews" && <section className="manager-panel"><h2>Review moderation</h2><p>Only approved reviews and their attachments appear publicly. Moderate for authenticity and privacy, not whether the rating is positive. The latest 200 submitted reviews are shown.</p><label>Filter<select value={reviewFilter} onChange={e => setReviewFilter(e.target.value)}>{["pending", "approved", "rejected", "hidden", "all"].map(s => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}</select></label><div className="review-grid">{selectedReviews.map(r => <article className="review-card" key={r.id}><span className="status-tag">{r.status} · {r.rating} / 5</span><h3>{r.name}</h3><p>{r.ceremony}</p><p className="review-message">{r.message}</p><div className="review-attachments">{r.attachments.map(a => a.kind === "image" ? <a key={a.id} href={a.url} target="_blank" rel="noopener noreferrer"><img src={a.url} alt={`Photo submitted by ${r.name}`} loading="lazy" /></a> : <video key={a.id} src={a.url} controls playsInline preload="none" />)}</div><div className="manager-actions"><button disabled={busy || r.status === "approved"} onClick={() => action({ entity: "review", id: r.id, status: "approved" }, "Review approved and published.")}>Approve</button><button disabled={busy || r.status === "rejected"} onClick={() => action({ entity: "review", id: r.id, status: "rejected" }, "Review rejected and kept private.")}>Reject</button><button disabled={busy || r.status === "hidden"} onClick={() => action({ entity: "review", id: r.id, status: "hidden" }, "Review hidden.")}>Hide</button></div></article>)}</div>{!selectedReviews.length && <p className="content-empty">No reviews in this category.</p>}</section>}
  </div>;
}
